#%RAML 1.0
title: doctus39
version: 1

/doctus/api:
  displayName: doctus training
  post:
    description: This api used to get the doctus 39 details.
    responses:
            200:
                    body:
                            application/json:
                                    example: "Doctus batch 39 is in progress"
                                                  
  